--CREATE DATABASE ShoppingOnline
Go

Use ShoppingOnline
Go

create table Category (
	id INT primary key,
	name VARCHAR(50)
);

insert into Category (id, name) values (1, 'Catera');
insert into Category (id, name) values (2, '626');
insert into Category (id, name) values (3, 'Vision');
insert into Category (id, name) values (4, 'Touareg 2');
insert into Category (id, name) values (5, '400SE');
insert into Category (id, name) values (6, 'H1');
insert into Category (id, name) values (7, 'Canyon');
insert into Category (id, name) values (8, 'Range Rover Sport');
insert into Category (id, name) values (9, '6 Series');
insert into Category (id, name) values (10, 'Express');



create table Product (
	id INT,
	name VARCHAR(max),
	quantity INT,
	price DECIMAL(3,1),
	description VARCHAR(max),
	imageUrl VARCHAR(max),
	created_date DATE,
	category_id INT foreign key references Category(id),
	primary key (id)
);



insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (1, 'Of Freaks and Men (Pro urodov i lyudey)', 16, 23.9, 'Other contact with other rodent, initial encounter', 'http://dummyimage.com/104x160.png/cc0000/ffffff', '2021-10-24', 4);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (2, 'Boccaccio ''70', 12, 42.2, 'Unspecified fracture of upper end of left radius, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing', 'http://dummyimage.com/237x194.png/5fa2dd/ffffff', '2022-03-03', 10);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (3, 'Michael Shayne: Private Detective', 8, 33.0, 'Patient room in hospital as the place of occurrence of the external cause', 'http://dummyimage.com/185x203.png/ff4444/ffffff', '2021-04-29', 6);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (4, 'Ways to Live Forever', 20, 48.7, 'Hantavirus (cardio)-pulmonary syndrome [HPS] [HCPS]', 'http://dummyimage.com/154x155.png/cc0000/ffffff', '2022-02-06', 8);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (5, 'Lizard, The (Marmoulak)', 20, 29.4, 'Passenger in pick-up truck or van injured in collision with pedestrian or animal in nontraffic accident', 'http://dummyimage.com/197x206.png/cc0000/ffffff', '2021-09-18', 4);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (6, 'Friendly Persuasion', 8, 19.2, 'Drowning and submersion after fall into swimming pool, undetermined intent, subsequent encounter', 'http://dummyimage.com/107x106.png/5fa2dd/ffffff', '2021-10-10', 9);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (7, 'Perfume', 10, 5.2, 'Sequelae of other cerebrovascular diseases', 'http://dummyimage.com/140x122.png/cc0000/ffffff', '2021-02-27', 2);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (8, 'Hall Pass', 19, 42.5, 'Legal intervention involving injury by rubber bullet, bystander injured, subsequent encounter', 'http://dummyimage.com/121x151.png/dddddd/000000', '2021-01-03', 8);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (9, 'Du côté de la côte', 9, 44.9, 'Cystic meniscus, anterior horn of lateral meniscus, left knee', 'http://dummyimage.com/108x216.png/cc0000/ffffff', '2021-02-28', 3);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (10, 'Man on the Flying Trapeze', 14, 39.1, 'Breakdown (mechanical) of implanted urinary sphincter, initial encounter', 'http://dummyimage.com/230x222.png/ff4444/ffffff', '2021-03-03', 7);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (11, 'Tamara Drewe', 17, 13.9, 'Benign neoplasm of larynx', 'http://dummyimage.com/208x224.png/dddddd/000000', '2021-07-06', 1);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (12, 'Chapter Two', 6, 46.7, 'Displacement of implanted penile prosthesis, sequela', 'http://dummyimage.com/228x173.png/cc0000/ffffff', '2022-07-21', 1);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (13, 'Key, The', 17, 9.4, 'Crushing injury of right knee', 'http://dummyimage.com/220x100.png/cc0000/ffffff', '2022-09-04', 10);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (14, 'Witless Protection', 6, 6.5, 'Sepsis following incomplete spontaneous abortion', 'http://dummyimage.com/204x183.png/ff4444/ffffff', '2022-06-30', 6);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (15, 'Seduced and Abandoned', 6, 15.5, 'Other intraoperative complications of respiratory system, not elsewhere classified', 'http://dummyimage.com/152x198.png/dddddd/000000', '2022-06-15', 7);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (16, 'Whistling in Brooklyn', 18, 36.4, 'Laceration of other part of colon, subsequent encounter', 'http://dummyimage.com/120x223.png/cc0000/ffffff', '2021-09-10', 7);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (17, 'Paranormal Activity', 20, 14.2, 'Other injury of flexor muscle, fascia and tendon of right little finger at wrist and hand level, subsequent encounter', 'http://dummyimage.com/105x133.png/dddddd/000000', '2021-09-17', 10);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (18, 'Bridge to the Sun', 7, 27.3, 'Arthritis due to other bacteria, left knee', 'http://dummyimage.com/179x163.png/cc0000/ffffff', '2021-03-30', 9);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (19, 'Hamlet, Prince of Denmark', 5, 24.6, 'Unspecified fracture of skull, initial encounter for closed fracture', 'http://dummyimage.com/211x187.png/ff4444/ffffff', '2021-08-24', 8);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (20, 'Iron Man', 15, 6.7, 'Displaced fracture (avulsion) of medial epicondyle of unspecified humerus, subsequent encounter for fracture with delayed healing', 'http://dummyimage.com/232x150.png/cc0000/ffffff', '2021-09-29', 6);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (21, 'Magnificent Seven, The', 18, 27.8, 'Major laceration of right carotid artery, subsequent encounter', 'http://dummyimage.com/136x165.png/ff4444/ffffff', '2021-05-30', 5);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (22, 'Border Radio', 17, 21.2, 'Asphyxiation due to unspecified cause, sequela', 'http://dummyimage.com/227x155.png/dddddd/000000', '2022-02-02', 8);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (23, 'Becky Sharp', 16, 24.5, 'Corrosion of third degree of left forearm, sequela', 'http://dummyimage.com/144x185.png/5fa2dd/ffffff', '2021-06-15', 7);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (24, 'Tarzan''s Magic Fountain', 6, 28.3, 'Terrorism involving suicide bomber, public safety official injured, initial encounter', 'http://dummyimage.com/242x115.png/ff4444/ffffff', '2022-09-03', 6);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (25, 'At Any Price', 8, 48.9, 'Medial dislocation of proximal end of tibia, unspecified knee, subsequent encounter', 'http://dummyimage.com/176x248.png/ff4444/ffffff', '2022-01-21', 5);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (26, 'Alibi, The (Lies and Alibis)', 19, 21.1, 'Stable burst fracture of third lumbar vertebra, subsequent encounter for fracture with routine healing', 'http://dummyimage.com/143x240.png/dddddd/000000', '2022-09-03', 2);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (27, 'Dune', 7, 9.4, 'Nondisplaced spiral fracture of shaft of radius, unspecified arm, initial encounter for open fracture type IIIA, IIIB, or IIIC', 'http://dummyimage.com/104x193.png/ff4444/ffffff', '2022-10-05', 5);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (28, 'Royal Affair, A (Kongelig affære, En)', 7, 5.5, 'Fracture of base of skull, unspecified side, sequela', 'http://dummyimage.com/131x182.png/5fa2dd/ffffff', '2021-06-04', 4);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (29, 'First Love, Last Rites', 15, 35.9, 'Rheumatism, unspecified', 'http://dummyimage.com/238x181.png/ff4444/ffffff', '2022-02-07', 2);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (30, 'But I''m a Cheerleader', 12, 46.0, 'Primary angle closure without glaucoma damage', 'http://dummyimage.com/113x114.png/cc0000/ffffff', '2021-01-22', 3);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (31, 'Blood Spattered Bride, The (La novia ensangrentada)', 14, 20.4, 'Severely displaced Zone III fracture of sacrum, subsequent encounter for fracture with delayed healing', 'http://dummyimage.com/125x132.png/dddddd/000000', '2022-04-25', 9);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (32, 'Violet & Daisy', 11, 23.7, 'Other physeal fracture of upper end of right femur, subsequent encounter for fracture with delayed healing', 'http://dummyimage.com/147x198.png/cc0000/ffffff', '2021-05-16', 9);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (33, 'I Am Waiting (Ore wa matteru ze)', 6, 42.4, 'Anaphylactic reaction due to eggs, sequela', 'http://dummyimage.com/116x143.png/ff4444/ffffff', '2021-03-10', 8);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (34, 'War of the Gargantuas, The (Furankenshutain no kaijû: Sanda tai Gaira)', 11, 10.3, 'Diarrhea, unspecified', 'http://dummyimage.com/179x140.png/ff4444/ffffff', '2021-08-03', 3);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (35, 'Headhunter''s Sister, The', 16, 38.3, 'Unspecified injury of unspecified blood vessel at wrist and hand level of left arm, sequela', 'http://dummyimage.com/176x129.png/5fa2dd/ffffff', '2021-04-19', 2);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (36, 'Unknown Woman, The (La Sconosciuta)', 5, 38.0, 'Terrorism, secondary effects, civilian injured, initial encounter', 'http://dummyimage.com/249x110.png/dddddd/000000', '2021-10-24', 6);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (37, 'Nanny, The', 10, 47.9, 'Paratyphoid fever C', 'http://dummyimage.com/220x246.png/ff4444/ffffff', '2022-10-30', 2);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (38, 'Sex, Lies, and Videotape', 19, 8.9, 'Nondisplaced fracture of distal phalanx of right little finger', 'http://dummyimage.com/123x116.png/5fa2dd/ffffff', '2022-09-09', 9);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (39, 'Blacula', 10, 16.1, 'Displaced simple supracondylar fracture without intercondylar fracture of right humerus, initial encounter for closed fracture', 'http://dummyimage.com/130x148.png/ff4444/ffffff', '2022-05-20', 10);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (40, 'Left-Hand Side of the Fridge, The (Moitié gauche du frigo, La)', 9, 43.4, 'Ectopic kidney', 'http://dummyimage.com/150x246.png/5fa2dd/ffffff', '2021-01-14', 7);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (41, 'Lone Wolf and Cub: Baby Cart in the Land of Demons (Kozure Ôkami: Meifumadô)', 10, 45.6, 'Diverticulitis of small intestine without perforation or abscess with bleeding', 'http://dummyimage.com/200x221.png/ff4444/ffffff', '2021-06-20', 5);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (42, 'Cheaper by the Dozen 2', 7, 32.8, 'Mantle cell lymphoma, spleen', 'http://dummyimage.com/224x145.png/dddddd/000000', '2022-06-01', 5);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (43, 'Peg o'' My Heart', 6, 39.5, 'Unspecified fracture of lower end of left tibia, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing', 'http://dummyimage.com/185x165.png/cc0000/ffffff', '2022-05-15', 3);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (44, 'Torrente 2: Misión Marbella', 7, 33.6, 'Unspecified foreign body in esophagus causing compression of trachea, initial encounter', 'http://dummyimage.com/240x108.png/5fa2dd/ffffff', '2022-06-13', 7);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (45, 'Chance of a Lifetime, The', 14, 23.4, 'Fall from, out of or through other building or structure', 'http://dummyimage.com/246x174.png/cc0000/ffffff', '2022-02-08', 5);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (46, 'Back to the Future Part III', 19, 35.0, 'Explosion and rupture of other specified pressurized devices, sequela', 'http://dummyimage.com/130x162.png/ff4444/ffffff', '2021-11-22', 4);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (47, '...All the Marbles (California Dolls, The)', 7, 22.9, 'Displaced fracture of lateral cuneiform of unspecified foot, subsequent encounter for fracture with malunion', 'http://dummyimage.com/105x111.png/5fa2dd/ffffff', '2022-06-04', 4);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (48, 'Lions For Lambs', 6, 14.7, 'Other specified injury of other blood vessels at ankle and foot level, unspecified leg, subsequent encounter', 'http://dummyimage.com/170x233.png/dddddd/000000', '2022-04-02', 10);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (49, 'Lonesome Jim', 6, 30.2, 'Lead-induced chronic gout, hand', 'http://dummyimage.com/106x119.png/dddddd/000000', '2022-06-13', 4);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (50, 'Grocer''s Son, The (Fils de l''épicier, Le)', 12, 16.1, 'Abnormal level of substances chiefly nonmedicinal as to source in specimens from other organs, systems and tissues', 'http://dummyimage.com/225x164.png/cc0000/ffffff', '2021-08-07', 10);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (51, 'Magnetic Man, The (Magneettimies)', 8, 5.4, 'Laceration of other blood vessels at wrist and hand level of unspecified arm', 'http://dummyimage.com/142x120.png/cc0000/ffffff', '2021-07-30', 8);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (52, 'Fiddler on the Roof', 6, 21.3, 'Adverse effect of other antidepressants, sequela', 'http://dummyimage.com/203x193.png/ff4444/ffffff', '2021-08-23', 10);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (53, 'Carmen Comes Home (Karumen kokyo ni kaeru)', 14, 49.4, 'Contusion and laceration of cerebrum, unspecified, with loss of consciousness of any duration with death due to other cause prior to regaining consciousness, initial encounter', 'http://dummyimage.com/194x243.png/ff4444/ffffff', '2022-06-01', 4);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (54, 'Blind Chance (Przypadek)', 6, 17.7, 'Salter-Harris Type III physeal fracture of right calcaneus, subsequent encounter for fracture with delayed healing', 'http://dummyimage.com/182x238.png/5fa2dd/ffffff', '2022-06-13', 10);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (55, 'Examined Life', 10, 39.6, 'Toxic effect of unspecified substance, intentional self-harm, sequela', 'http://dummyimage.com/145x215.png/cc0000/ffffff', '2022-08-17', 7);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (56, 'Paheli', 9, 22.2, 'Nondisplaced fracture of base of third metacarpal bone, left hand, subsequent encounter for fracture with routine healing', 'http://dummyimage.com/215x200.png/5fa2dd/ffffff', '2022-02-18', 1);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (57, 'Fetishes', 17, 16.0, 'Unspecified foreign body in respiratory tract, part unspecified causing other injury, sequela', 'http://dummyimage.com/239x132.png/ff4444/ffffff', '2021-03-21', 1);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (58, 'Voyage to the Bottom of the Sea', 13, 43.0, 'Aneurysmal bone cyst, other site', 'http://dummyimage.com/142x215.png/cc0000/ffffff', '2022-01-28', 5);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (59, 'Dungeons & Dragons', 11, 48.1, 'Superficial foreign body of left elbow, initial encounter', 'http://dummyimage.com/143x210.png/cc0000/ffffff', '2022-06-13', 8);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (60, 'Mark, The', 11, 49.4, 'Other accident to commercial fixed-wing aircraft injuring occupant, initial encounter', 'http://dummyimage.com/187x241.png/ff4444/ffffff', '2021-02-04', 3);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (61, 'Comebacks, The', 12, 36.9, 'Burn involving larynx and trachea with lung, sequela', 'http://dummyimage.com/103x126.png/5fa2dd/ffffff', '2021-04-20', 9);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (62, 'Ismael', 15, 28.0, 'Neoplastic (malignant) related fatigue', 'http://dummyimage.com/191x174.png/dddddd/000000', '2022-07-09', 5);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (63, 'The Land Before Time VI: The Secret of Saurus Rock', 18, 30.3, 'Felty''s syndrome, right hip', 'http://dummyimage.com/242x131.png/ff4444/ffffff', '2021-06-10', 9);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (64, 'Hoop Dreams', 7, 17.1, 'Displaced fracture of lateral condyle of unspecified femur, subsequent encounter for open fracture type I or II with routine healing', 'http://dummyimage.com/217x156.png/dddddd/000000', '2021-10-08', 8);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (65, 'Mean Creek', 12, 5.3, 'Unspecified injury of muscle, fascia and tendon of unspecified hip, initial encounter', 'http://dummyimage.com/191x106.png/5fa2dd/ffffff', '2021-09-21', 2);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (66, 'Christmas Story 2, A', 14, 28.7, 'Arthropathy following intestinal bypass, right ankle and foot', 'http://dummyimage.com/214x227.png/5fa2dd/ffffff', '2022-04-03', 2);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (67, 'Bible, The (a.k.a. Bible... In the Beginning, The)', 7, 39.6, 'Fracture of unspecified phalanx of other finger, subsequent encounter for fracture with nonunion', 'http://dummyimage.com/247x240.png/5fa2dd/ffffff', '2022-10-25', 5);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (68, 'Kissed by Winter (Vinterkyss)', 5, 23.6, 'Sprain of right coracohumeral (ligament), subsequent encounter', 'http://dummyimage.com/199x115.png/cc0000/ffffff', '2022-06-18', 4);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (69, 'Home Sweet Home', 16, 27.3, 'Other mechanical complication of intraperitoneal dialysis catheter, initial encounter', 'http://dummyimage.com/159x241.png/5fa2dd/ffffff', '2022-03-09', 5);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (70, 'Wings (Krylya)', 8, 26.3, 'Cerebral infarction due to thrombosis of right posterior cerebral artery', 'http://dummyimage.com/144x220.png/ff4444/ffffff', '2021-11-26', 6);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (71, 'Fear[s] of the Dark (Peur[s] du noir)', 9, 12.8, 'Unspecified injury of left forearm, sequela', 'http://dummyimage.com/241x133.png/ff4444/ffffff', '2022-03-11', 6);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (72, 'Hustle & Flow', 6, 42.1, 'Gastric contents in larynx causing other injury, subsequent encounter', 'http://dummyimage.com/209x226.png/ff4444/ffffff', '2021-01-22', 7);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (73, 'Hamlet', 20, 5.2, 'Other night blindness', 'http://dummyimage.com/119x141.png/cc0000/ffffff', '2022-01-22', 1);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (74, 'Stander', 11, 43.3, 'Legal intervention involving injury by handgun, law enforcement official injured, initial encounter', 'http://dummyimage.com/175x129.png/ff4444/ffffff', '2022-04-07', 4);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (75, 'Danny Deckchair', 17, 46.2, 'Congenital malformation of intestine, unspecified', 'http://dummyimage.com/166x106.png/5fa2dd/ffffff', '2021-10-26', 3);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (76, 'Pictures of the Old World (Obrazy starého sveta)', 20, 21.7, 'Minor opacity of cornea, bilateral', 'http://dummyimage.com/167x248.png/ff4444/ffffff', '2021-01-30', 9);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (77, 'Chasing Liberty', 7, 20.1, 'Acute pulmonary manifestations due to radiation', 'http://dummyimage.com/141x221.png/5fa2dd/ffffff', '2021-02-24', 10);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (78, 'Prince of Central Park, The', 11, 24.9, 'Puncture wound with foreign body of unspecified thumb with damage to nail, subsequent encounter', 'http://dummyimage.com/143x204.png/cc0000/ffffff', '2022-03-10', 2);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (79, 'Dedication', 16, 22.4, 'Rotaviral enteritis', 'http://dummyimage.com/170x249.png/ff4444/ffffff', '2022-09-11', 2);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (80, 'Silent Movie', 15, 39.2, 'Term delivery with preterm labor, second trimester, fetus 4', 'http://dummyimage.com/161x152.png/ff4444/ffffff', '2021-07-29', 3);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (81, 'Death of a Salesman', 13, 14.6, 'Nondisplaced oblique fracture of shaft of right femur, subsequent encounter for open fracture type I or II with delayed healing', 'http://dummyimage.com/133x250.png/ff4444/ffffff', '2021-03-10', 2);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (82, 'Surviving Progress', 18, 19.8, 'Collapsed vertebra, not elsewhere classified, thoracic region, initial encounter for fracture', 'http://dummyimage.com/249x206.png/dddddd/000000', '2022-06-11', 1);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (83, 'Six Days Seven Nights', 16, 36.1, 'Puncture wound with foreign body, right thigh, sequela', 'http://dummyimage.com/215x103.png/ff4444/ffffff', '2022-03-09', 1);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (84, 'Debt, The (Dlug)', 6, 23.6, 'Dislocation of C5/C6 cervical vertebrae, sequela', 'http://dummyimage.com/192x239.png/ff4444/ffffff', '2021-09-12', 6);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (85, 'Mystic Pizza', 11, 27.2, 'Open bite of left little finger without damage to nail, initial encounter', 'http://dummyimage.com/103x118.png/dddddd/000000', '2022-07-25', 9);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (86, 'Scarecrow', 14, 15.0, 'Nondisplaced fracture of lateral condyle of unspecified humerus, subsequent encounter for fracture with malunion', 'http://dummyimage.com/120x152.png/ff4444/ffffff', '2021-01-23', 2);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (87, 'Chinese Roulette (Chinesisches Roulette)', 6, 26.6, 'Pulmonary complications of anesthesia during pregnancy', 'http://dummyimage.com/233x203.png/dddddd/000000', '2021-08-27', 3);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (88, 'Storm Rider', 12, 17.8, 'Accidental puncture and laceration of a respiratory system organ or structure during a procedure', 'http://dummyimage.com/124x157.png/ff4444/ffffff', '2021-06-19', 4);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (89, 'Blues Harp', 8, 43.4, 'Torus fracture of lower end of unspecified radius, initial encounter for closed fracture', 'http://dummyimage.com/171x105.png/ff4444/ffffff', '2022-05-26', 7);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (90, 'Scary or Die', 13, 5.7, 'Corrosion of unspecified degree of multiple sites of unspecified ankle and foot, sequela', 'http://dummyimage.com/136x233.png/ff4444/ffffff', '2022-02-23', 8);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (91, 'Finger, The (Dedo, El)', 17, 30.6, 'Displaced fracture of neck of left radius, sequela', 'http://dummyimage.com/150x136.png/5fa2dd/ffffff', '2021-01-18', 7);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (92, 'Tarzan', 18, 5.5, 'Unspecified open wound of unspecified part of head, sequela', 'http://dummyimage.com/141x110.png/dddddd/000000', '2021-04-02', 10);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (93, 'Gorgeous (Boh lee chun)', 13, 23.9, 'War operations involving intentional restriction of air and airway, military personnel, initial encounter', 'http://dummyimage.com/199x156.png/dddddd/000000', '2021-10-03', 1);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (94, 'Bio Zombie (Sun faa sau si)', 18, 43.1, 'Legal intervention involving unspecified explosives, suspect injured, subsequent encounter', 'http://dummyimage.com/118x154.png/5fa2dd/ffffff', '2022-05-27', 9);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (95, 'Daylight', 17, 6.2, 'Intentional self-harm by exposure to extremes of cold, initial encounter', 'http://dummyimage.com/114x229.png/cc0000/ffffff', '2021-02-03', 6);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (96, 'Night and Day (Bam gua nat)', 10, 34.6, 'Puncture wound without foreign body of vagina and vulva, subsequent encounter', 'http://dummyimage.com/183x232.png/dddddd/000000', '2021-02-27', 7);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (97, 'Old Boy', 14, 33.3, 'Type 2 diabetes mellitus with stable proliferative diabetic retinopathy, right eye', 'http://dummyimage.com/174x150.png/5fa2dd/ffffff', '2021-11-18', 7);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (98, 'Ballad of Narayama, The (Narayama Bushiko)', 8, 6.3, 'Puncture wound with foreign body of abdominal wall, unspecified quadrant with penetration into peritoneal cavity, initial encounter', 'http://dummyimage.com/214x170.png/dddddd/000000', '2022-03-14', 7);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (99, 'When Darkness Falls (När mörkret faller)', 14, 32.4, 'Low lying placenta with hemorrhage, unspecified trimester', 'http://dummyimage.com/169x177.png/cc0000/ffffff', '2021-02-21', 8);
insert into Product (id, name, quantity, price, description, imageUrl, created_date, category_id) values (100, 'Godzilla''s Revenge (Gojira-Minira-Gabara: Oru Kaijû Daishingeki) (All Monsters Attack)', 19, 36.8, 'Nondisplaced fracture of medial malleolus of right tibia, subsequent encounter for open fracture type I or II with delayed healing', 'http://dummyimage.com/223x207.png/cc0000/ffffff', '2022-03-25', 4);